### ISSUE TITLE
No internet access

### ISSUE THREAD

**Issue by ghost** [kabukki/blih#1]
Little bug when you don't have internet access and do, for example, api.ping().
You get an undefined value for your response resulting in the following error:

> ./node_modules/blih/index.js:55
>                 if (response.statusCode >= 200 && response.statusCode < 300) {
>                              ^
> TypeError: Cannot read property 'statusCode' of undefined

**Comment by kabukki** [comment]
It should be fixed in ced57bbefa804fcff3171615670c8af47b688e81.  
Thanks for the feedback !
